import { BaseLLMProvider } from './base.js';
import { LLMProviderType, GenerateJSONOptions, LLMResponse } from '../types.js';

export class DeterministicMockProvider extends BaseLLMProvider {
  readonly id: LLMProviderType = 'deterministic';
  readonly modelName: string = 'deterministic-legal-engine-v1';

  async isAvailable(): Promise<boolean> {
    return true;
  }

  protected async executePrompt(
    prompt: string,
    systemPrompt?: string,
    temperature?: number,
    maxTokens?: number
  ): Promise<string> {
    const lower = prompt.toLowerCase();

    // 1. Fact sync / structured extraction
    if (lower.includes('sync') || lower.includes('extract') || lower.includes('facts')) {
      return JSON.stringify({
        updatedFacts: {},
        changesApplied: ['Facts analyzed against canonical document structure.'],
        confidence: 0.98
      });
    }

    // 2. Clause explanation
    if (lower.includes('explain') || lower.includes('plain language')) {
      return JSON.stringify({
        plainLanguage: 'This operative provision establishes binding legal rights and obligations under applicable jurisdiction.',
        purpose: 'Provides clarity and enforceable commitments between the parties.',
        legalImplication: 'Binding and enforceable upon formal execution.',
        sourcesUsed: ['Atharv Approved Legal Library', 'Indian Contract Act, 1872'],
        disclaimer: 'Informational analysis by Atharv Legal AI. Review with a qualified lawyer.'
      });
    }

    // 3. Edit / patch proposal
    if (lower.includes('edit') || lower.includes('instruction') || lower.includes('patch')) {
      return JSON.stringify({
        action: 'REPLACE_TEXT',
        replacementText: 'Updated operative contractual text pursuant to user instructions.',
        explanation: 'Deterministically aligned clause with legal requirements.',
        confidence: 0.95
      });
    }

    // 4. Default contract text drafting
    return `Pursuant to the mutual covenants established herein, the parties agree to all standard obligations, confidentiality protections, and statutory covenants in full compliance with applicable law.`;
  }

  override async generateJSON<T>(options: GenerateJSONOptions<T>): Promise<LLMResponse<T>> {
    const prompt = options.prompt;
    const lower = prompt.toLowerCase();

    // Custom Mock generator tailored for any Zod schema:
    let candidate: any = {};

    if (options.schemaName === 'ClauseExplanation' || lower.includes('plainlanguage')) {
      candidate = {
        plainLanguage: 'This clause defines operative non-disclosure and confidentiality obligations between the parties.',
        purpose: 'Protects proprietary assets, trade secrets, and technical data from unauthorized dissemination.',
        legalImplication: 'Breach permits the disclosing party to pursue damages and emergency injunctive relief.',
        sourcesUsed: ['Atharv Approved Legal Library', 'Indian Contract Act, 1872'],
        disclaimer: 'Generated by Atharv Legal AI for research/drafting assistance. Review with a qualified lawyer.'
      };
    } else if (options.schemaName === 'DocumentEditPlan' || lower.includes('operations')) {
      candidate = {
        operations: [
          {
            op: 'replace_in_section',
            target: 'duration',
            old: '2 years',
            new: '3 years',
            sectionId: 'sec_duration'
          }
        ],
        explanation: 'Updated duration to 3 years as requested.',
        confidence: 0.95
      };
    } else {
      // Generic mock fallback that attempts parsing schema shape
      candidate = {
        status: 'SUCCESS',
        result: 'Deterministic legal synthesis completed.',
        confidence: 0.95,
        notes: 'Generated via Atharv Legal AI deterministic engine'
      };
    }

    // If options.schema can parse candidate, return it; otherwise fallback to executePrompt + base parse
    try {
      const validated = options.schema.parse(candidate);
      return {
        data: validated,
        rawText: JSON.stringify(validated),
        modelUsed: this.modelName,
        provider: this.id,
        cached: false,
        latencyMs: 5
      };
    } catch {
      return super.generateJSON(options);
    }
  }
}
